---
- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - "vars/params.yml"
    - "vars/creds.json"


  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Debug
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug

    - name: Create Auth Profile
      avi_authprofile:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        name: "{{ item.name }}"
        tenant: "{{ item.tenant_ref | default('admin') }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        type: "{{ item.type }}"
        saml:
          sp:
            saml_entity_type: "{{ item.saml.sp.saml_entity_type }}"
          idp:
            metadata: "{{ lookup('file', 'vars/metadata') }}"
      loop: "{{ authProfile }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.type == "AUTH_PROFILE_SAML"
      register: authOutput

    - name: Debug
      debug:
        msg: "{{ authOutput.results.0.obj.uuid }}"
      tags:
        - debug
